# This workflow will build and push a static web page to Amazon S3
# and then invalidate the cloudfront distribution.

on:
  pull_request:
  push:
    branches:
      - master

name: Deploy to Amazon S3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install -g gulp bower
          npm init
          npm build && npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install Gulp
      run: gulp
    - name: Deploy site to S3 bucket
      if: contains(github.ref, 'master')
      env:
        SOURCE_DIR: './dist'
        AWS_DEFAULT_REGION: us-east-1
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_CLOUDFRONT_DIST_ID: ${{ secrets.AWS_CLOUDFRONT_DIST_ID }}
      run: |
       aws s3 cp --recursive --region ${AWS_DEFAULT_REGION} ${SOURCE_DIR} s3://${AWS_BUCKET}
       aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DIST_ID} --paths "/*"
